In [1]:
import numpy as np
from sklearn.feature_selection import chi2
from sklearn.impute import SimpleImputer

In [3]:
attr,label=[],[]
with open('dermatology.data') as fptr:
    reader=fptr.readlines()
    for line in reader:
        label.append(int(line.split(',')[-1]))
        attr_vector=line.split(',')[:-1]
        for i in range(len(attr_vector)):
            if attr_vector[i]=='?':
                attr_vector[i]=np.nan
            else:
                attr_vector[i]=int(attr_vector[i])
        attr.append(attr_vector)
X=np.array(attr)
Y=np.array(label)

In [4]:
print(X)

[[ 2.  2.  0. ...  1.  0. 55.]
 [ 3.  3.  3. ...  1.  0.  8.]
 [ 2.  1.  2. ...  2.  3. 26.]
 ...
 [ 3.  2.  2. ...  2.  3. 28.]
 [ 2.  1.  3. ...  2.  3. 50.]
 [ 3.  2.  2. ...  3.  0. 35.]]


In [5]:
print(Y)

[2 1 3 1 3 2 5 3 4 4 1 2 2 1 3 4 2 1 3 5 6 2 5 3 5 1 6 5 2 3 1 2 1 1 4 2 3
 2 3 1 2 4 1 2 5 3 4 6 2 3 3 4 1 1 5 1 2 3 4 2 6 1 5 1 2 3 1 4 5 1 2 6 3 5
 4 2 2 1 3 5 1 2 2 2 5 1 1 3 1 4 2 2 5 1 3 4 2 5 1 6 2 5 1 2 2 1 4 1 3 1 1
 3 5 3 3 5 2 3 4 1 2 5 6 1 1 2 6 3 5 4 1 1 3 5 5 1 4 2 3 1 2 1 1 3 3 3 2 5
 4 2 2 1 1 1 5 3 2 3 2 2 4 2 3 6 2 1 1 3 4 3 3 1 1 1 3 1 1 2 3 3 1 1 1 1 6
 2 2 2 2 1 3 3 3 1 1 2 3 2 2 2 5 5 5 5 5 1 1 1 1 1 1 1 3 3 3 3 3 3 4 4 4 4
 5 5 5 5 5 5 5 2 2 2 2 1 1 1 1 1 1 6 6 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 4 4 4
 4 4 4 5 5 5 5 6 6 6 4 4 4 1 1 1 1 1 2 2 4 4 4 1 1 2 2 2 3 3 3 3 1 1 1 1 5
 5 5 5 5 3 3 3 4 1 1 4 4 4 1 1 1 3 3 3 3 3 1 1 1 1 4 4 1 1 4 3 3 4 1 1 4 4
 5 5 1 1 5 5 3 1 5 5 6 6 4 4 6 6 6 1 1 1 5 5 1 1 1 1 2 2 4 4 3 3 1]


In [6]:
print(len(X))

366


In [7]:
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
attr_clean=imp.fit_transform(X)

In [8]:
print(np.nan in X)

False


In [9]:
for i in range(len(X)):
    if np.nan in X[i]:
        print('haha')
    else:
        continue

In [11]:
attr_clean

array([[ 2.,  2.,  0., ...,  1.,  0., 55.],
       [ 3.,  3.,  3., ...,  1.,  0.,  8.],
       [ 2.,  1.,  2., ...,  2.,  3., 26.],
       ...,
       [ 3.,  2.,  2., ...,  2.,  3., 28.],
       [ 2.,  1.,  3., ...,  2.,  3., 50.],
       [ 3.,  2.,  2., ...,  3.,  0., 35.]])

In [12]:
np.nan in attr_clean

False

In [13]:
from sklearn.feature_selection import SelectKBest

In [15]:
result=SelectKBest(score_func=chi2,k=10)

In [16]:
fit=result.fit(attr_clean,Y)

In [17]:
print(fit.scores_)

[ 12.68338231  28.57099668  73.88232098 111.24733386 161.8008628
 669.66666667 537.37088813 563.5        356.05135572 324.2091792
  67.8123706  604.33333333  60.13971743 188.14932908 687.99989577
 198.65368034  12.81023425  47.42565418  71.24648694 513.12379935
 401.30537871 513.1839712  176.6473138  276.2754143  577.99571759
 199.66573629 671.80000713 275.4361674  667.74228547 552.41109987
 690.57857143   8.90538676 759.36493847 431.1195411 ]


In [18]:
features=fit.transform(attr_clean)

In [21]:
features[0:366,:]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [3., 3., 1., ..., 0., 0., 3.],
       ...,
       [2., 2., 2., ..., 0., 0., 3.],
       [3., 2., 2., ..., 0., 0., 3.],
       [0., 0., 0., ..., 0., 0., 0.]])