In [1]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA

In [2]:
attr,label=[],[]
with open('dermatology.data') as fptr:
    reader=fptr.readlines()
    for line in reader:
        label.append(int(line.split(',')[-1]))
        attr_vector=line.split(',')[:-1]
        for i in range(len(attr_vector)):
            if attr_vector[i]=='?':
                attr_vector[i]=np.nan
            else:
                attr_vector[i]=int(attr_vector[i])
        attr.append(attr_vector)
X=np.array(attr)
Y=np.array(label)
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
attr_clean=imp.fit_transform(X)
print(attr_clean)
print(Y)

[[ 2.  2.  0. ...  1.  0. 55.]
 [ 3.  3.  3. ...  1.  0.  8.]
 [ 2.  1.  2. ...  2.  3. 26.]
 ...
 [ 3.  2.  2. ...  2.  3. 28.]
 [ 2.  1.  3. ...  2.  3. 50.]
 [ 3.  2.  2. ...  3.  0. 35.]]
[2 1 3 1 3 2 5 3 4 4 1 2 2 1 3 4 2 1 3 5 6 2 5 3 5 1 6 5 2 3 1 2 1 1 4 2 3
 2 3 1 2 4 1 2 5 3 4 6 2 3 3 4 1 1 5 1 2 3 4 2 6 1 5 1 2 3 1 4 5 1 2 6 3 5
 4 2 2 1 3 5 1 2 2 2 5 1 1 3 1 4 2 2 5 1 3 4 2 5 1 6 2 5 1 2 2 1 4 1 3 1 1
 3 5 3 3 5 2 3 4 1 2 5 6 1 1 2 6 3 5 4 1 1 3 5 5 1 4 2 3 1 2 1 1 3 3 3 2 5
 4 2 2 1 1 1 5 3 2 3 2 2 4 2 3 6 2 1 1 3 4 3 3 1 1 1 3 1 1 2 3 3 1 1 1 1 6
 2 2 2 2 1 3 3 3 1 1 2 3 2 2 2 5 5 5 5 5 1 1 1 1 1 1 1 3 3 3 3 3 3 4 4 4 4
 5 5 5 5 5 5 5 2 2 2 2 1 1 1 1 1 1 6 6 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 4 4 4
 4 4 4 5 5 5 5 6 6 6 4 4 4 1 1 1 1 1 2 2 4 4 4 1 1 2 2 2 3 3 3 3 1 1 1 1 5
 5 5 5 5 3 3 3 4 1 1 4 4 4 1 1 1 3 3 3 3 3 1 1 1 1 4 4 1 1 4 3 3 4 1 1 4 4
 5 5 1 1 5 5 3 1 5 5 6 6 4 4 6 6 6 1 1 1 5 5 1 1 1 1 2 2 4 4 3 3 1]


In [3]:
print(len(attr_clean))

366


In [5]:
pca=PCA(n_components=10)
orthogonal_attr=pca.fit(attr_clean)
print(orthogonal_attr.components_)

[[-1.94470663e-04  7.60882184e-04  8.28275204e-03  3.63956445e-03
   4.90645173e-03  6.18974912e-03 -1.40203883e-02  6.18321030e-03
  -5.00301786e-03  2.25207753e-03 -1.98914946e-03  6.96393921e-03
   1.20450530e-03  2.69990562e-03  1.72234958e-03 -3.01502085e-03
   2.18659038e-03 -6.57339720e-04  2.27532979e-03  8.71689395e-03
   9.50145787e-03  9.00161525e-03  3.67048821e-03  4.55459929e-03
   5.64972542e-03  8.19748704e-03  8.13025927e-03 -6.34674061e-03
   7.11822798e-03 -1.06347971e-02 -1.26943955e-02  3.78121443e-03
   7.71925264e-03  9.99310158e-01]
 [-2.15006757e-02 -6.21400063e-02 -2.16490972e-02  1.65350304e-01
   9.28433990e-02  2.51632723e-01 -1.09837340e-02  2.14491652e-01
  -2.23377115e-01 -2.05720486e-01 -3.49454004e-02  2.28950632e-01
   2.04208035e-02 -1.27365108e-01 -1.02502705e-02  2.77890694e-01
  -1.71942620e-02 -6.90461775e-02 -1.22455583e-01 -2.77643695e-01
  -3.04782112e-01 -2.66246342e-01 -1.11306699e-01 -1.46279265e-01
   2.21132121e-01 -1.35658686e-01  2.5478

In [6]:
print(len(orthogonal_attr.components_[0]))

34
